name: Docker build CI

on:
  push:
    paths:
      - 'configs/docker/**'
      - '.github/workflows/**'
    branches:
      - master
      - development

  steps:
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -
      name: Build and push alertmanager
      uses: docker/build-push-action@v2
      with:
        context: ./configs/docker/alertmanager
        file: ./configs/docker/alertmanager/Dockerfile
        push: true
        tags: babobene/alertmanager:development

    -
      name: Build and push dockerd-exporter
      uses: docker/build-push-action@v2
      with:
        context: ./configs/docker/dockerd-exporter
        file: ./configs/docker/dockerd-exporter/Dockerfile
        push: true
        tags: babobene/dockerd-exporter:development

    -
      name: Build and push grafana
      uses: docker/build-push-action@v2
      with:
        context: ./configs/docker/grafana
        file: ./configs/docker/grafana/Dockerfile
        push: true
        tags: babobene/grafana:development

    -
      name: Build and push node-exporter
      uses: docker/build-push-action@v2
      with:
        context: ./configs/docker/node-exporter
        file: ./configs/docker/node-exporter/Dockerfile
        push: true
        tags: babobene/node-exporter:development

    -
      name: Build and push prometheus
      uses: docker/build-push-action@v2
      with:
        context: ./configs/docker/prometheus
        file: ./configs/docker/prometheus/Dockerfile
        push: true
        tags: babobene/prometheus:development
