name: Docker build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Docker images
        run: |
          cd config/docker/alertmanager && docker build -t babobene/alertmanager:${GITHUB_REF##*/} .
          cd ../dockerd-exporter && docker build -t babobene/dockerd-exporter:${GITHUB_REF##*/} .
          cd ../grafana && docker build -t babobene/grafana:${GITHUB_REF##*/} .
          cd ../node-exporter && docker build -t babobene/node-exporter:${GITHUB_REF##*/} .
          cd ../prometheus && docker build -t babobene/prometheus:${GITHUB_REF##*/} .
      - name: Push Docker images
        run: |
          docker push babobene/alertmanager:${GITHUB_REF##*/}
          docker push babobene/dockerd-exporter:${GITHUB_REF##*/}
          docker push babobene/grafana:${GITHUB_REF##*/}
          docker push babobene/node-exporter:${GITHUB_REF##*/}
          docker push babobene/prometheus:${GITHUB_REF##*/}